### ISSUE TITLE
Migrate to Swift

### ISSUE THREAD

**Issue by danielgalasko** [danielgalasko/uitableviewcellseperatoreffectfun#3]

**Comment by weishaung** [comment]
heollo。




------------------ 原始邮件 ------------------
发件人: "Daniel Galasko";<notifications@github.com>;
发送时间: 2016年1月18日(星期一) 下午4:04
收件人: "danielgalasko/uitableviewcellseperatoreffectfun"<uitableviewcellseperatoreffectfun@noreply.github.com>; 

主题: [uitableviewcellseperatoreffectfun] Migrate to Swift (#3)

**Comment by danielgalasko** [comment]
@weishaung Im not sure that came out right?

**Comment by weishaung** [comment]
I don't know who you are, I got your mail. Out of curiosity, I replied to you. I'm glad to meet you.



------------------ 原始邮件 ------------------
发件人: "Daniel Galasko";<notifications@github.com>;
发送时间: 2016年1月20日(星期三) 晚上9:15
收件人: "danielgalasko/uitableviewcellseperatoreffectfun"<uitableviewcellseperatoreffectfun@noreply.github.com>; 
抄送: "巍"<572825279@qq.com>; 
主题: Re: [uitableviewcellseperatoreffectfun] Migrate to Swift (#3)




@weishaung Im not sure that came out right?

**Comment by danielgalasko** [comment]
@weishaung yes because you are following this repository, you will get mails for everything:)
